-- MySQL Script generated by MySQL Workbench
-- Fri Dec 22 14:28:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Global_Super_Store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Global_Super_Store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Global_Super_Store` DEFAULT CHARACTER SET utf8 ;
USE `Global_Super_Store` ;

-- -----------------------------------------------------
-- Table `Global_Super_Store`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`Customers` (
  `CustomerID` INT NOT NULL,
  `First Name` VARCHAR(45) NOT NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`OrderPriorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`OrderPriorities` (
  `OrderPriorityID` INT NOT NULL,
  `OrderPriorityName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OrderPriorityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`Orders` (
  `OrderID` INT NOT NULL,
  `OrderDate` DATE NOT NULL,
  `TotalCost` DECIMAL(10,2) NOT NULL,
  `Discount` DECIMAL(10,2) NOT NULL,
  `Segment` VARCHAR(45) NOT NULL,
  `CustomerID` INT NOT NULL,
  `OrderPriorityID` INT NOT NULL,
  PRIMARY KEY (`OrderID`, `OrderPriorityID`),
  INDEX `fk_Orders_Customers1_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_Orders_OrderPriorities1_idx` (`OrderPriorityID` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `Global_Super_Store`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_OrderPriorities1`
    FOREIGN KEY (`OrderPriorityID`)
    REFERENCES `Global_Super_Store`.`OrderPriorities` (`OrderPriorityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`ProductSubCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`ProductSubCategories` (
  `SubCategoryID` INT NOT NULL,
  `SubCategoryName` VARCHAR(45) NOT NULL,
  `CategoryID` INT NOT NULL,
  PRIMARY KEY (`SubCategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`Products` (
  `ProductID` INT NOT NULL,
  `ProductName` VARCHAR(45) NOT NULL,
  `SubCategoryID` INT NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Products_ProductSubCategories1_idx` (`SubCategoryID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_ProductSubCategories1`
    FOREIGN KEY (`SubCategoryID`)
    REFERENCES `Global_Super_Store`.`ProductSubCategories` (`SubCategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`OrderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`OrderItems` (
  `OrderItemID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  `UnitPrice` DECIMAL(10,2) NOT NULL,
  `Quantity` INT NOT NULL,
  `TotalPrice` DECIMAL(10,2) NOT NULL,
  `ProductID` INT NOT NULL,
  PRIMARY KEY (`OrderItemID`, `ProductID`),
  INDEX `fk_OrderItems_Orders1_idx` (`OrderID` ASC) VISIBLE,
  INDEX `fk_OrderItems_Products1_idx` (`ProductID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItems_Orders1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `Global_Super_Store`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItems_Products1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Global_Super_Store`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`ProductCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`ProductCategories` (
  `CategoryID` INT NOT NULL,
  `CategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CategoryID`),
  CONSTRAINT `fk_ProductCategories_ProductSubCategories1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `Global_Super_Store`.`ProductSubCategories` (`SubCategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`Addresses` (
  `AddressID` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `PostCode` VARCHAR(45) NULL,
  `Region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AddressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`Shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`Shipping` (
  `ShippingID` INT NOT NULL,
  `ShippingCost` VARCHAR(45) NULL,
  `ShippingDate` DATE NULL,
  `ShippingMode` VARCHAR(45) NULL,
  `OrderID` INT NOT NULL,
  `AddressID` INT NOT NULL,
  PRIMARY KEY (`ShippingID`, `OrderID`, `AddressID`),
  INDEX `fk_Shipping_Orders1_idx` (`OrderID` ASC) VISIBLE,
  INDEX `fk_Shipping_Addresses1_idx` (`AddressID` ASC) VISIBLE,
  CONSTRAINT `fk_Shipping_Orders1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `Global_Super_Store`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipping_Addresses1`
    FOREIGN KEY (`AddressID`)
    REFERENCES `Global_Super_Store`.`Addresses` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Global_Super_Store`.`Customers_has_Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Global_Super_Store`.`Customers_has_Addresses` (
  `CustomerID` INT NOT NULL,
  `AddressID` INT NOT NULL,
  PRIMARY KEY (`CustomerID`, `AddressID`),
  INDEX `fk_Customers_has_Addresses_Addresses1_idx` (`AddressID` ASC) VISIBLE,
  INDEX `fk_Customers_has_Addresses_Customers_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_has_Addresses_Customers`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `Global_Super_Store`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_has_Addresses_Addresses1`
    FOREIGN KEY (`AddressID`)
    REFERENCES `Global_Super_Store`.`Addresses` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
