# Generated by Django 4.2.7 on 2023-11-27 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_alter_menuitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime.now),
        ),
    ]
