version: "3.1"
name: "lab5-mysql"
services:
  db:
    container_name: mysql_database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: littlelemon
      MYSQL_DATABASE: feedback
    ports:
      - 3306:3306
